import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

interface FormationPlayer {
  position: string;
  x: number;
  y: number;
}

const FORMATIONS: Record<string, FormationPlayer[]> = {
  FORMATION_343: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DC', x: 26, y: 76 },
    { position: 'DC', x: 50, y: 79 },
    { position: 'DC', x: 74, y: 76 },
    { position: 'ML', x: 14, y: 55 },
    { position: 'MC', x: 39, y: 58 },
    { position: 'MC', x: 61, y: 58 },
    { position: 'MR', x: 86, y: 55 },
    { position: 'AML', x: 21, y: 25 },
    { position: 'ST', x: 50, y: 15 },
    { position: 'AMR', x: 79, y: 25 },
  ],
  FORMATION_352: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DC', x: 26, y: 76 },
    { position: 'DC', x: 50, y: 79 },
    { position: 'DC', x: 74, y: 76 },
    { position: 'ML', x: 14, y: 55 },
    { position: 'MC', x: 35, y: 55 },
    { position: 'MC', x: 50, y: 55 },
    { position: 'MC', x: 65, y: 55 },
    { position: 'MR', x: 86, y: 55 },
    { position: 'ST', x: 40, y: 18 },
    { position: 'ST', x: 60, y: 18 },
  ],
  FORMATION_3412: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DC', x: 26, y: 76 },
    { position: 'DC', x: 50, y: 79 },
    { position: 'DC', x: 74, y: 76 },
    { position: 'ML', x: 14, y: 55 },
    { position: 'MC', x: 39, y: 58 },
    { position: 'MC', x: 61, y: 58 },
    { position: 'MR', x: 86, y: 55 },
    { position: 'AMC', x: 50, y: 35 },
    { position: 'ST', x: 40, y: 18 },
    { position: 'ST', x: 60, y: 18 },
  ],
  FORMATION_442: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'ML', x: 15, y: 50 },
    { position: 'MC', x: 40, y: 55 },
    { position: 'MC', x: 60, y: 55 },
    { position: 'MR', x: 85, y: 50 },
    { position: 'ST', x: 40, y: 18 },
    { position: 'ST', x: 60, y: 18 },
  ],
  FORMATION_433: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'MC', x: 35, y: 53 },
    { position: 'MC', x: 50, y: 53 },
    { position: 'MC', x: 65, y: 53 },
    { position: 'AML', x: 21, y: 25 },
    { position: 'ST', x: 50, y: 15 },
    { position: 'AMR', x: 79, y: 25 },
  ],
  FORMATION_4231: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'DM', x: 40, y: 60 },
    { position: 'DM', x: 60, y: 60 },
    { position: 'AML', x: 20, y: 37 },
    { position: 'AMC', x: 50, y: 37 },
    { position: 'AMR', x: 80, y: 37 },
    { position: 'ST', x: 50, y: 15 },
  ],
  FORMATION_4141: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'DM', x: 50, y: 62 },
    { position: 'ML', x: 15, y: 48 },
    { position: 'MC', x: 40, y: 48 },
    { position: 'MC', x: 60, y: 48 },
    { position: 'MR', x: 85, y: 48 },
    { position: 'ST', x: 50, y: 15 },
  ],
  FORMATION_4312: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'MC', x: 35, y: 53 },
    { position: 'MC', x: 50, y: 53 },
    { position: 'MC', x: 65, y: 53 },
    { position: 'AMC', x: 50, y: 35 },
    { position: 'ST', x: 40, y: 18 },
    { position: 'ST', x: 60, y: 18 },
  ],
  FORMATION_451: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'ML', x: 15, y: 50 },
    { position: 'MC', x: 35, y: 53 },
    { position: 'MC', x: 50, y: 53 },
    { position: 'MC', x: 65, y: 53 },
    { position: 'MR', x: 85, y: 50 },
    { position: 'ST', x: 50, y: 15 },
  ],
  FORMATION_4123: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'DL', x: 15, y: 75 },
    { position: 'DC', x: 38, y: 78 },
    { position: 'DC', x: 62, y: 78 },
    { position: 'DR', x: 85, y: 75 },
    { position: 'DM', x: 50, y: 62 },
    { position: 'MC', x: 35, y: 48 },
    { position: 'MC', x: 65, y: 48 },
    { position: 'AML', x: 21, y: 25 },
    { position: 'ST', x: 50, y: 15 },
    { position: 'AMR', x: 79, y: 25 },
  ],
  FORMATION_532: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'WBL', x: 10, y: 70 },
    { position: 'DC', x: 30, y: 78 },
    { position: 'DC', x: 50, y: 80 },
    { position: 'DC', x: 70, y: 78 },
    { position: 'WBR', x: 90, y: 70 },
    { position: 'MC', x: 35, y: 50 },
    { position: 'MC', x: 50, y: 50 },
    { position: 'MC', x: 65, y: 50 },
    { position: 'ST', x: 40, y: 18 },
    { position: 'ST', x: 60, y: 18 },
  ],
  FORMATION_523: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'WBL', x: 10, y: 70 },
    { position: 'DC', x: 30, y: 78 },
    { position: 'DC', x: 50, y: 80 },
    { position: 'DC', x: 70, y: 78 },
    { position: 'WBR', x: 90, y: 70 },
    { position: 'MC', x: 40, y: 50 },
    { position: 'MC', x: 60, y: 50 },
    { position: 'AML', x: 21, y: 25 },
    { position: 'ST', x: 50, y: 15 },
    { position: 'AMR', x: 79, y: 25 },
  ],
  FORMATION_541: [
    { position: 'GK', x: 50, y: 92 },
    { position: 'WBL', x: 10, y: 70 },
    { position: 'DC', x: 30, y: 78 },
    { position: 'DC', x: 50, y: 80 },
    { position: 'DC', x: 70, y: 78 },
    { position: 'WBR', x: 90, y: 70 },
    { position: 'ML', x: 15, y: 45 },
    { position: 'MC', x: 40, y: 50 },
    { position: 'MC', x: 60, y: 50 },
    { position: 'MR', x: 85, y: 45 },
    { position: 'ST', x: 50, y: 15 },
  ],
};

@Component({
  selector: 'app-formation-pitch',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './formation-pitch.component.html',
  styleUrl: './formation-pitch.component.css',
})
export class FormationPitchComponent {
  @Input() formation?: string;

  players(): FormationPlayer[] {
    return FORMATIONS[this.formation ?? ''] ?? FORMATIONS['FORMATION_442'];
  }
}
