package com.ftn.sbnz.kjar.rules;

import com.ftn.sbnz.model.enums.DefensiveLineHeight;
import com.ftn.sbnz.model.enums.Mentality;
import com.ftn.sbnz.model.forward.TacticalAssistantInput;
import com.ftn.sbnz.model.forward.Level1Facts;
import com.ftn.sbnz.model.forward.Level2Facts;
import com.ftn.sbnz.model.forward.Level3Facts;


rule "Low defensive line - incapable"
    salience 30
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.highLineCapability == false
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.LOW );
    };

end


rule "Low defensive line - cautious mentality"
    salience 29
    no-loop true

when
    Level2Facts( 
    selectedMentality == Mentality.CAUTIOUS
    ||
    selectedMentality == Mentality.DEFENSIVE
    ||
    selectedMentality == Mentality.VERY_DEFENSIVE
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.LOW );
    };

end


rule "High defensive line - attacking mentality"
    salience 28
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.highLineCapability == true
     )

    Level2Facts( 
    selectedMentality == Mentality.ATTACKING
    ||
    selectedMentality == Mentality.VERY_ATTACKING
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.HIGH );
    };

end


rule "High defensive line - positive mentality without counter threat"
    salience 27
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.highLineCapability == true
     )

    Level2Facts( 
    selectedMentality == Mentality.POSITIVE
     )

    Level1Facts( 
    hasCounterOpportunity == false
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.HIGH );
    };

end


rule "Standard defensive line - counter threat"
    salience 26
    no-loop true

when
    TacticalAssistantInput(
    teamProfile.highLineCapability == true
     )

    Level1Facts( 
    hasCounterOpportunity == true
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.STANDARD );
    };

end


rule "Standard defensive line - balanced mentality"
    salience 25
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.highLineCapability == true
     )

    Level2Facts( 
    selectedMentality == Mentality.BALANCED
     )

    $facts : Level3Facts(
    defensiveLineHeight == null
     )

then
    modify($facts) {
        setDefensiveLineHeight( DefensiveLineHeight.STANDARD );
    };

end
