package com.ftn.sbnz.kjar.rules;

import com.ftn.sbnz.model.enums.AttackType;
import com.ftn.sbnz.model.enums.Mentality;
import com.ftn.sbnz.model.enums.PhysicalProfile;
import com.ftn.sbnz.model.enums.PressingIntensity;
import com.ftn.sbnz.model.enums.TransitionAfterLossOfBall;
import com.ftn.sbnz.model.forward.TacticalAssistantInput;
import com.ftn.sbnz.model.forward.Level1Facts;
import com.ftn.sbnz.model.forward.Level2Facts;
import com.ftn.sbnz.model.forward.Level3Facts;


rule "Counter press - balanced and fast"
    salience 20
    no-loop true

when
    Level2Facts( 
    selectedMentality == Mentality.BALANCED
     )

    TacticalAssistantInput( 
    teamProfile.physicalProfile == PhysicalProfile.FAST
     )

    $facts : Level3Facts(
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.COUNTER_PRESS
         );
    };

end


rule "Counter press - attacking mentality"
    salience 19
    no-loop true

when
    Level2Facts( 
    selectedMentality == Mentality.ATTACKING
    ||
    selectedMentality == Mentality.VERY_ATTACKING
     )

    $facts : Level3Facts( 
    pressingIntensity == PressingIntensity.HIGH,
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.COUNTER_PRESS
         );
    };

end


rule "Counter press - pressing forwards"
    salience 18
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.attackType == AttackType.PRESSING_ATTACKERS
     )

    $facts : Level3Facts( 
    pressingIntensity == PressingIntensity.HIGH,
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.COUNTER_PRESS
         );
    };

end


rule "Hold shape - counter opportunity"
    salience 17
    no-loop true

when
    Level1Facts( 
    hasCounterOpportunity == true
     )

    Level2Facts( 
    selectedMentality == Mentality.DEFENSIVE
    ||
    selectedMentality == Mentality.CAUTIOUS
     )

    $facts : Level3Facts(
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.HOLD_SHAPE
         );
    };

end


rule "Regroup - low chemistry"
    salience 16
    no-loop true

when
    Level1Facts( 
    hasLowFitness == true
     )

    $facts : Level3Facts(
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.REGROUP
         );
    };

end


rule "Default transition"
    salience 10

when
    $facts : Level3Facts( 
    transitionAfterLossOfBall == null
     )

then
    modify($facts) {
        setTransitionAfterLossOfBall( 
        TransitionAfterLossOfBall.REGROUP
         );
    };

end
