package com.ftn.sbnz.kjar.rules;

import com.ftn.sbnz.model.TacticalAssistantInput;
import com.ftn.sbnz.model.MatchContext.LocationType;
import com.ftn.sbnz.model.MatchContext.MatchImportance;
import com.ftn.sbnz.model.MatchContext.CompetitionType;
import com.ftn.sbnz.model.OpponentProfile.OpponentWeakness;
import com.ftn.sbnz.model.OpponentProfile.DefenseLineEngagement;
import com.ftn.sbnz.model.OpponentProfile.PlayingStyle;
import com.ftn.sbnz.model.Level1Facts;


rule "Medium chemistry"
    salience 95
    no-loop true

when
    $input : TacticalAssistantInput( 
    teamProfile.tacticalFitness >= 40 && teamProfile.tacticalFitness <= 69
     )

    $facts : Level1Facts()

then
    modify($facts) {
        setHasMediumFitness( true )
    };

    System.out.println( "[LEVEL 1] SREDNJA_UIGRANOST = true" );

end


rule "Difficult away match"
    salience 90
    no-loop true

when
    $input : TacticalAssistantInput( 
    matchContext.location == LocationType.AWAY,
    matchContext.importance == MatchImportance.HIGH
     )

    $facts : Level1Facts( 
    isUnderdog == true
     )

then
    modify($facts) {
        setIsDifficultAwayMatch( true )
    };

end


rule "Must win"
    salience 95
    no-loop true

when
    $input : TacticalAssistantInput( 
    matchContext.competitionType == CompetitionType.CUP,
    matchContext.importance == MatchImportance.HIGH
     )

    $facts : Level1Facts()

then
    modify($facts) {
        setMustWin( true )
    };

end


rule "Dominant position"
    salience 90
    no-loop true

when
    $input : TacticalAssistantInput( 
    matchContext.location == LocationType.HOME
     )

    $facts : Level1Facts( 
    isFavorite == true
     )

then
    modify($facts) {
        setHasDominantPosition( true )
    };

end


rule "Can settle for draw"
    salience 90
    no-loop true

when
    $input : TacticalAssistantInput( 
    matchContext.importance == MatchImportance.MEDIUM,
    matchContext.competitionType == CompetitionType.LEAGUE
     )

    $facts : Level1Facts( 
    isEvenlyMatched == true
     )

then
    modify($facts) {
        setCanDrawMatch( true )
    };

end


rule "Careful match"
    salience 90
    no-loop true

when
    $input : TacticalAssistantInput( 
    matchContext.importance == MatchImportance.HIGH
     )

    $facts : Level1Facts( 
    isUnderdog == true
     )

then
    modify($facts) {
        setIsCautiousMatch( true )
    };

end


rule "Counter attack opportunity"
    salience 95
    no-loop true

when
    $input : TacticalAssistantInput( 
    opponentProfile.weakness == OpponentWeakness.SLOW_DEFENDERS
    ||
    opponentProfile.weakness == OpponentWeakness.VULNERABLE_ON_FLANKS
     )

    $facts : Level1Facts()

then
    modify($facts) {
        setHasCounterOpportunity( true )
    };

end


rule "Aggressive opponent"
    salience 95
    no-loop true

when
    $input : TacticalAssistantInput( 
    opponentProfile.lineEngagement == DefenseLineEngagement.HIGH_PRESS,
    opponentProfile.playingStyle == PlayingStyle.POSSESSION_BASED
     )

    $facts : Level1Facts()

then
    modify($facts) {
        setIsAggressiveOpponent( true )
    };

end


rule "Passive opponent"
    salience 95
    no-loop true

when
    $input : TacticalAssistantInput( 
    opponentProfile.lineEngagement == DefenseLineEngagement.LOW_BLOCK,
    opponentProfile.playingStyle != PlayingStyle.COUNTER_ATTACK
     )

    $facts : Level1Facts()

then
    modify($facts) {
        setIsPassiveOpponent( true )
    };

end