package com.ftn.sbnz.kjar.rules;

import com.ftn.sbnz.model.enums.Mentality;
import com.ftn.sbnz.model.enums.MidfieldQuality;
import com.ftn.sbnz.model.enums.PassingDirectness;
import com.ftn.sbnz.model.enums.PlayingStyle;
import com.ftn.sbnz.model.forward.TacticalAssistantInput;
import com.ftn.sbnz.model.forward.Level1Facts;
import com.ftn.sbnz.model.forward.Level2Facts;
import com.ftn.sbnz.model.forward.Level3Facts;


rule "Direct passing - low chemistry"
    salience 30
    no-loop true

when
    Level1Facts( 
    hasLowFitness == true
     )

    $facts : Level3Facts(
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.DIRECT );
    };

end


rule "Direct passing - aggressive possession opponent"
    salience 29
    no-loop true

when
    Level1Facts( 
    isAggressiveOpponent == true
     )

    TacticalAssistantInput( 
    opponentProfile.playingStyle == PlayingStyle.POSSESSION_BASED
     )

    $facts : Level3Facts(
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.DIRECT );
    };

end


rule "Direct passing - counter opportunity and defensive mentality"
    salience 28
    no-loop true

when
    Level1Facts( 
    hasCounterOpportunity == true
     )

    Level2Facts( 
    selectedMentality == Mentality.DEFENSIVE
    ||
    selectedMentality == Mentality.CAUTIOUS
     )

    $facts : Level3Facts(
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.DIRECT );
    };

end


rule "Short passing - creative midfield and good chemistry"
    salience 27
    no-loop true

when
    TacticalAssistantInput( 
    teamProfile.midfieldQuality == MidfieldQuality.CREATIVE
     )

    Level1Facts( 
    hasHighFitness == true
     )

    Level2Facts( 
    selectedMentality == Mentality.POSITIVE
    ||
    selectedMentality == Mentality.ATTACKING
     )

    $facts : Level3Facts(
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.SHORTER );
    };

end


rule "Short passing - passive opponent"
    salience 26
    no-loop true

when
    Level1Facts( 
    isPassiveOpponent == true
     )

    TacticalAssistantInput( 
    teamProfile.midfieldQuality == MidfieldQuality.CREATIVE
     )

    $facts : Level3Facts(
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.SHORTER );
    };

end


rule "Default passing"
    salience 10

when
    $facts : Level3Facts( 
    passingDirectness == null
     )

then
    modify($facts) {
        setPassingDirectness( PassingDirectness.STANDARD );
    };

end
