package com.ftn.sbnz.kjar.rules.forward;

import com.ftn.sbnz.model.enums.Formation;
import com.ftn.sbnz.model.forward.Level2Facts;
import com.ftn.sbnz.model.forward.FormationScore;

rule "FC L2 - Select highest scoring formation"
    salience 50
    no-loop true

when
    $bestFormation : Formation() from accumulate( 
    FormationScore( $formation : formation, $score : totalScore ),
    init( Formation best = null; int max = Integer.MIN_VALUE; ),
    action( if ( $score > max ) { max = $score; best = $formation; } ),
    result( best )
     )

    $bestScore : Integer() from accumulate( 
    FormationScore( $score : totalScore ),
    init( int max = Integer.MIN_VALUE; ),
    action( if ( $score > max ) { max = $score; } ),
    result( max )
     )

    $facts : Level2Facts( 
    selectedFormation == null
     )

then
    modify($facts) {
        setSelectedFormation( $bestFormation ),
        setFormationScore( $bestScore );
    };

    System.out.println( "[FC:L2] selectedFormation=" + $bestFormation + " | score=" + $bestScore );

end
